// data/adsData.js

export const adsData = [
  // ===== املاک =====
  {
    id: 1,
    title: 'آپارتمان ۱۰۰ متری در نیاوران',
    price: 2500000000,
    category: 'املاک',
    subCategory: 'فروش مسکونی',
    city: 'تهران',
    district: 'نیاوران',
    description: 'آپارتمان نوساز با دید عالی به کوه، پارکینگ، انباری، آسانسور',
    image: 'https://picsum.photos/seed/real1/400/300',
    hasPhoto: true,
    date: '2026-06-23',
    views: 245,
    isActive: true,
  },
  {
    id: 2,
    title: 'ویلا ۵۰۰ متری در کرج',
    price: 8500000000,
    category: 'املاک',
    subCategory: 'فروش مسکونی',
    city: 'کرج',
    district: 'مهرشهر',
    description: 'ویلا با استخر و باغچه بزرگ، ۳ طبقه، ۵ خوابه',
    image: 'https://picsum.photos/seed/real2/400/300',
    hasPhoto: true,
    date: '2024-06-19',
    views: 189,
    isActive: true,
  },
  {
    id: 3,
    title: 'زمین ۱۰۰۰ متری در دماوند',
    price: 1200000000,
    category: 'املاک',
    subCategory: 'زمین و باغ',
    city: 'دماوند',
    district: 'مرکزی',
    description: 'زمین با سند تک برگ، کاربری مسکونی، نزدیک به جاده',
    image: 'https://picsum.photos/seed/real3/400/300',
    hasPhoto: false,
    date: '2024-06-18',
    views: 67,
    isActive: true,
  },
  {
    id: 4,
    title: 'مغازه ۴۰ متری در بازار تهران',
    price: 1800000000,
    category: 'املاک',
    subCategory: 'فروش اداری و تجاری',
    city: 'تهران',
    district: 'بازار',
    description: 'مغازه با ۱۵ متر جلوخان، مناسب هر نوع کسب و کار',
    image: 'https://picsum.photos/seed/real4/400/300',
    hasPhoto: true,
    date: '2024-06-17',
    views: 312,
    isActive: true,
  },

  // ===== وسایل نقلیه =====
  {
    id: 5,
    title: 'پراید ۱۳۹۵ صفر',
    price: 350000000,
    category: 'وسایل نقلیه',
    subCategory: 'خودرو',
    city: 'تهران',
    district: 'شهرک غرب',
    description: 'پراید سفید، کارکرد ۴۵۰۰۰ کیلومتر، سالم و تمیز',
    image: 'https://picsum.photos/seed/car1/400/300',
    hasPhoto: true,
    date: '2024-06-20',
    views: 567,
    isActive: true,
  },
  {
    id: 6,
    title: 'موتورسیکلت رایزن ۲۰۰',
    price: 98000000,
    category: 'وسایل نقلیه',
    subCategory: 'موتورسیکلت',
    city: 'اصفهان',
    district: 'خواجو',
    description: 'موتور کارکرد ۱۲ هزار کیلومتر، روغن و فیلتر تعویض شده',
    image: 'https://picsum.photos/seed/car2/400/300',
    hasPhoto: true,
    date: '2024-06-16',
    views: 134,
    isActive: true,
  },
  {
    id: 7,
    title: 'آریو ۱۳۹۸ دنده‌ای',
    price: 420000000,
    category: 'وسایل نقلیه',
    subCategory: 'خودرو',
    city: 'شیراز',
    district: 'معالی‌آباد',
    description: 'آریو سفید، کارکرد ۶۸۰۰۰ کیلومتر، کاملاً سالم',
    image: 'https://picsum.photos/seed/car3/400/300',
    hasPhoto: true,
    date: '2024-06-15',
    views: 298,
    isActive: true,
  },

  // ===== کالای دیجیتال =====
  {
    id: 8,
    title: 'آیفون ۱۴ پرو مکس ۲۵۶',
    price: 65000000,
    category: 'کالای دیجیتال',
    subCategory: 'موبایل و تبلت',
    city: 'تهران',
    district: 'ونک',
    description: 'گوشی دربسته، گارانتی ۱۸ ماهه، فاکتور دارد',
    image: 'https://picsum.photos/seed/digital1/400/300',
    hasPhoto: true,
    date: '2024-06-20',
    views: 890,
    isActive: true,
  },
  {
    id: 9,
    title: 'لپ‌تاپ ایسوس زن‌بوک',
    price: 28000000,
    category: 'کالای دیجیتال',
    subCategory: 'رایانه',
    city: 'تهران',
    district: 'پاسداران',
    description: 'لپ‌تاپ با رم ۱۶ گیگ، SSD 512، کور i7 نسل ۱۱',
    image: 'https://picsum.photos/seed/digital2/400/300',
    hasPhoto: true,
    date: '2024-06-18',
    views: 156,
    isActive: true,
  },
  {
    id: 10,
    title: 'هدفون سونی WH-1000XM4',
    price: 8500000,
    category: 'کالای دیجیتال',
    subCategory: 'لوازم جانبی',
    city: 'اصفهان',
    district: 'چهارباغ',
    description: 'نو، دربسته، فاقد کالا، گارانتی ۲ ساله',
    image: 'https://picsum.photos/seed/digital3/400/300',
    hasPhoto: true,
    date: '2024-06-14',
    views: 203,
    isActive: true,
  },

  // ===== خانه و آشپزخانه =====
  {
    id: 11,
    title: 'یخچال ساید بای ساید ال جی',
    price: 45000000,
    category: 'خانه و آشپزخانه',
    subCategory: 'لوازم خانگی برقی',
    city: 'تهران',
    district: 'جردن',
    description: 'یخچال با قابلیت آب یخ، یخ‌ساز، استیل ضد خش',
    image: 'https://picsum.photos/seed/home1/400/300',
    hasPhoto: true,
    date: '2024-06-19',
    views: 178,
    isActive: true,
  },
  {
    id: 12,
    title: 'مبل ۷ نفره استیل',
    price: 32000000,
    category: 'خانه و آشپزخانه',
    subCategory: 'مبلمان و صنایع چوب',
    city: 'کرج',
    district: 'گوهردشت',
    description: 'مبل با پارچه مخمل، پایه استیل، رنگ طوسی',
    image: 'https://picsum.photos/seed/home2/400/300',
    hasPhoto: false,
    date: '2024-06-17',
    views: 89,
    isActive: true,
  },

  // ===== خدمات =====
  {
    id: 13,
    title: 'سرویس کامل خودرو در محل',
    price: 350000,
    category: 'خدمات',
    subCategory: 'خدمات خودرو',
    city: 'تهران',
    district: 'شهرک غرب',
    description: 'تعویض روغن، فیلترها، واشرها در محل شما',
    image: 'https://picsum.photos/seed/service1/400/300',
    hasPhoto: true,
    date: '2024-06-20',
    views: 45,
    isActive: true,
  },
  {
    id: 14,
    title: 'تدریس خصوصی ریاضی',
    price: 250000,
    category: 'خدمات',
    subCategory: 'خدمات آموزشی',
    city: 'تهران',
    district: 'سعادت‌آباد',
    description: 'تدریس ریاضی برای تمام پایه‌ها، ۱۰ سال سابقه',
    image: 'https://picsum.photos/seed/service2/400/300',
    hasPhoto: false,
    date: '2024-06-16',
    views: 34,
    isActive: true,
  },

  // ===== وسایل شخصی =====
  {
    id: 15,
    title: 'کیف چرم زنانه اصل',
    price: 1250000,
    category: 'وسایل شخصی',
    subCategory: 'کیف، کفش، لباس',
    city: 'شیراز',
    district: 'زند',
    description: 'کیف چرم طبیعی، رنگ مشکی، برند معتبر',
    image: 'https://picsum.photos/seed/personal1/400/300',
    hasPhoto: true,
    date: '2024-06-19',
    views: 67,
    isActive: true,
  },

  // ===== سرگرمی و فراغت =====
  {
    id: 16,
    title: 'بلیط کنسرت در تهران',
    price: 450000,
    category: 'سرگرمی و فراغت',
    subCategory: 'بلیت و تور',
    city: 'تهران',
    district: 'میلاد',
    description: 'بلیط ردیف جلوی کنسرت، تاریخ ۱۰ تیر، ۲ عدد موجود',
    image: 'https://picsum.photos/seed/entertain1/400/300',
    hasPhoto: true,
    date: '2024-06-18',
    views: 123,
    isActive: true,
  },

  // ===== تجهیزات صنعتی =====
  {
    id: 17,
    title: 'دستگاه جوش اینورتر ۲۰۰ آمپر',
    price: 18000000,
    category: 'تجهیزات صنعتی',
    subCategory: 'ماشین‌آلات صنعتی',
    city: 'اصفهان',
    district: 'صنعتی',
    description: 'دستگاه جوش با ۲ سال گارانتی، کارکرد ۲۰ ساعت',
    image: 'https://picsum.photos/seed/industrial1/400/300',
    hasPhoto: true,
    date: '2024-06-15',
    views: 78,
    isActive: true,
  },

  // ===== استخدام و کاریابی =====
  {
    id: 18,
    title: 'استخدام برنامه‌نویس ارشد React',
    price: 80000000,
    category: 'استخدام و کاریابی',
    subCategory: 'استخدام',
    city: 'تهران',
    district: 'آزادی',
    description: 'شرکت دانش‌بنیان برای پروژه جدید نیاز به برنامه‌نویس ارشد دارد',
    image: 'https://picsum.photos/seed/job1/400/300',
    hasPhoto: false,
    date: '2024-06-20',
    views: 567,
    isActive: true,
  },
];