// data/adsData.js

export const adsData = [
  // ===== املاک (50 آگهی) =====
  {
    id: 1,
    title: 'آپارتمان ۱۰۰ متری در نیاوران',
    price: 2500000000,
    category: 'املاک',
    subCategory: 'فروش مسکونی',
    city: 'تهران',
    district: 'نیاوران',
    description: 'آپارتمان نوساز با دید عالی به کوه، پارکینگ، انباری، آسانسور',
    image: 'https://picsum.photos/seed/real1/400/300',
    hasPhoto: true,
    date: '2026-06-23',
    views: 245,
    isActive: true,
  },
  {
    id: 2,
    title: 'ویلا ۵۰۰ متری در کرج',
    price: 8500000000,
    category: 'املاک',
    subCategory: 'فروش مسکونی',
    city: 'کرج',
    district: 'مهرشهر',
    description: 'ویلا با استخر و باغچه بزرگ، ۳ طبقه، ۵ خوابه',
    image: 'https://picsum.photos/seed/real2/400/300',
    hasPhoto: true,
    date: '2024-06-19',
    views: 189,
    isActive: true,
  },
  {
    id: 3,
    title: 'زمین ۱۰۰۰ متری در دماوند',
    price: 1200000000,
    category: 'املاک',
    subCategory: 'زمین و باغ',
    city: 'دماوند',
    district: 'مرکزی',
    description: 'زمین با سند تک برگ، کاربری مسکونی، نزدیک به جاده',
    image: 'https://picsum.photos/seed/real3/400/300',
    hasPhoto: false,
    date: '2024-06-18',
    views: 67,
    isActive: true,
  },
  {
    id: 4,
    title: 'مغازه ۴۰ متری در بازار تهران',
    price: 1800000000,
    category: 'املاک',
    subCategory: 'فروش اداری و تجاری',
    city: 'تهران',
    district: 'بازار',
    description: 'مغازه با ۱۵ متر جلوخان، مناسب هر نوع کسب و کار',
    image: 'https://picsum.photos/seed/real4/400/300',
    hasPhoto: true,
    date: '2024-06-17',
    views: 312,
    isActive: true,
  },
  {
    id: 5,
    title: 'آپارتمان ۷۰ متری در جردن',
    price: 3200000000,
    category: 'املاک',
    subCategory: 'فروش مسکونی',
    city: 'تهران',
    district: 'جردن',
    description: 'آپارتمان لوکس با امکانات کامل، پارکینگ اختصاصی',
    image: 'https://picsum.photos/seed/real5/400/300',
    hasPhoto: true,
    date: '2024-06-16',
    views: 178,
    isActive: true,
  },
  {
    id: 6,
    title: 'دفتر کار ۱۲۰ متری در ونک',
    price: 4500000000,
    category: 'املاک',
    subCategory: 'فروش اداری و تجاری',
    city: 'تهران',
    district: 'ونک',
    description: 'دفتر کار مدرن با امکانات کامل، پارکینگ اختصاصی',
    image: 'https://picsum.photos/seed/real6/400/300',
    hasPhoto: true,
    date: '2024-06-15',
    views: 95,
    isActive: true,
  },
  {
    id: 7,
    title: 'کلنگی ۳۰۰ متری در پاسداران',
    price: 8000000000,
    category: 'املاک',
    subCategory: 'زمین و باغ',
    city: 'تهران',
    district: 'پاسداران',
    description: 'زمین کلنگی با مجوز ساخت ۶ طبقه',
    image: 'https://picsum.photos/seed/real7/400/300',
    hasPhoto: false,
    date: '2024-06-14',
    views: 56,
    isActive: true,
  },
  {
    id: 8,
    title: 'مغازه ۲۵ متری در تجریش',
    price: 2500000000,
    category: 'املاک',
    subCategory: 'فروش اداری و تجاری',
    city: 'تهران',
    district: 'تجریش',
    description: 'مغازه با موقعیت عالی در بازار تجریش',
    image: 'https://picsum.photos/seed/real8/400/300',
    hasPhoto: true,
    date: '2024-06-13',
    views: 210,
    isActive: true,
  },
  {
    id: 9,
    title: 'آپارتمان ۱۵۰ متری در سعادت‌آباد',
    price: 5500000000,
    category: 'املاک',
    subCategory: 'فروش مسکونی',
    city: 'تهران',
    district: 'سعادت‌آباد',
    description: 'آپارتمان با نمای مدرن، ۲ پارکینگ',
    image: 'https://picsum.photos/seed/real9/400/300',
    hasPhoto: true,
    date: '2024-06-12',
    views: 310,
    isActive: true,
  },
  {
    id: 10,
    title: 'ویلا ۳۰۰ متری در شمال تهران',
    price: 12000000000,
    category: 'املاک',
    subCategory: 'فروش مسکونی',
    city: 'تهران',
    district: 'شمال',
    description: 'ویلا با استخر و سونا، چشم‌انداز عالی',
    image: 'https://picsum.photos/seed/real10/400/300',
    hasPhoto: true,
    date: '2024-06-11',
    views: 420,
    isActive: true,
  },
  {
    id: 11,
    title: 'زمین ۲۰۰۰ متری در شهرک غرب',
    price: 15000000000,
    category: 'املاک',
    subCategory: 'زمین و باغ',
    city: 'تهران',
    district: 'شهرک غرب',
    description: 'زمین با کاربری تجاری-مسکونی',
    image: 'https://picsum.photos/seed/real11/400/300',
    hasPhoto: true,
    date: '2024-06-10',
    views: 78,
    isActive: true,
  },
  {
    id: 12,
    title: 'مغازه ۵۰ متری در شهر ری',
    price: 1200000000,
    category: 'املاک',
    subCategory: 'فروش اداری و تجاری',
    city: 'تهران',
    district: 'شهر ری',
    description: 'مغازه با موقعیت مناسب برای کسب و کار',
    image: 'https://picsum.photos/seed/real12/400/300',
    hasPhoto: false,
    date: '2024-06-09',
    views: 89,
    isActive: true,
  },
  {
    id: 13,
    title: 'آپارتمان ۸۰ متری در کرج',
    price: 1800000000,
    category: 'املاک',
    subCategory: 'فروش مسکونی',
    city: 'کرج',
    district: 'گوهردشت',
    description: 'آپارتمان با امکانات کامل، نزدیک به مترو',
    image: 'https://picsum.photos/seed/real13/400/300',
    hasPhoto: true,
    date: '2024-06-08',
    views: 145,
    isActive: true,
  },
  {
    id: 14,
    title: 'دفتر کار ۸۰ متری در اصفهان',
    price: 2000000000,
    category: 'املاک',
    subCategory: 'فروش اداری و تجاری',
    city: 'اصفهان',
    district: 'مرکزی',
    description: 'دفتر کار با امکانات کامل',
    image: 'https://picsum.photos/seed/real14/400/300',
    hasPhoto: true,
    date: '2024-06-07',
    views: 67,
    isActive: true,
  },
  {
    id: 15,
    title: 'آپارتمان ۱۲۰ متری در شیراز',
    price: 2200000000,
    category: 'املاک',
    subCategory: 'فروش مسکونی',
    city: 'شیراز',
    district: 'معالی‌آباد',
    description: 'آپارتمان با امکانات کامل، نزدیک به پارک',
    image: 'https://picsum.photos/seed/real15/400/300',
    hasPhoto: true,
    date: '2024-06-06',
    views: 134,
    isActive: true,
  },
  {
    id: 16,
    title: 'مغازه ۳۰ متری در مشهد',
    price: 900000000,
    category: 'املاک',
    subCategory: 'فروش اداری و تجاری',
    city: 'مشهد',
    district: 'مرکزی',
    description: 'مغازه با موقعیت عالی در بازار مشهد',
    image: 'https://picsum.photos/seed/real16/400/300',
    hasPhoto: false,
    date: '2024-06-05',
    views: 78,
    isActive: true,
  },
  {
    id: 17,
    title: 'زمین ۵۰۰ متری در تبریز',
    price: 600000000,
    category: 'املاک',
    subCategory: 'زمین و باغ',
    city: 'تبریز',
    district: 'مرکزی',
    description: 'زمین با کاربری مسکونی',
    image: 'https://picsum.photos/seed/real17/400/300',
    hasPhoto: true,
    date: '2024-06-04',
    views: 56,
    isActive: true,
  },
  {
    id: 18,
    title: 'ویلا ۴۰۰ متری در شمال',
    price: 9000000000,
    category: 'املاک',
    subCategory: 'فروش مسکونی',
    city: 'تهران',
    district: 'شمال',
    description: 'ویلا با استخر و باغچه بزرگ',
    image: 'https://picsum.photos/seed/real18/400/300',
    hasPhoto: true,
    date: '2024-06-03',
    views: 320,
    isActive: true,
  },
  {
    id: 19,
    title: 'آپارتمان ۹۰ متری در غرب تهران',
    price: 2800000000,
    category: 'املاک',
    subCategory: 'فروش مسکونی',
    city: 'تهران',
    district: 'غرب',
    description: 'آپارتمان با امکانات کامل',
    image: 'https://picsum.photos/seed/real19/400/300',
    hasPhoto: true,
    date: '2024-06-02',
    views: 167,
    isActive: true,
  },
  {
    id: 20,
    title: 'مغازه ۶۰ متری در تهرانپارس',
    price: 1500000000,
    category: 'املاک',
    subCategory: 'فروش اداری و تجاری',
    city: 'تهران',
    district: 'تهرانپارس',
    description: 'مغازه با موقعیت عالی',
    image: 'https://picsum.photos/seed/real20/400/300',
    hasPhoto: false,
    date: '2024-06-01',
    views: 89,
    isActive: true,
  },
  {
    id: 21,
    title: 'زمین ۳۰۰۰ متری در لواسان',
    price: 25000000000,
    category: 'املاک',
    subCategory: 'زمین و باغ',
    city: 'تهران',
    district: 'لواسان',
    description: 'زمین با کاربری ویلا',
    image: 'https://picsum.photos/seed/real21/400/300',
    hasPhoto: true,
    date: '2024-05-30',
    views: 45,
    isActive: true,
  },
  {
    id: 22,
    title: 'آپارتمان ۶۰ متری در نازی‌آباد',
    price: 900000000,
    category: 'املاک',
    subCategory: 'فروش مسکونی',
    city: 'تهران',
    district: 'نازی‌آباد',
    description: 'آپارتمان با امکانات کامل',
    image: 'https://picsum.photos/seed/real22/400/300',
    hasPhoto: true,
    date: '2024-05-29',
    views: 123,
    isActive: true,
  },
  {
    id: 23,
    title: 'دفتر کار ۵۰ متری در ستارخان',
    price: 1500000000,
    category: 'املاک',
    subCategory: 'فروش اداری و تجاری',
    city: 'تهران',
    district: 'ستارخان',
    description: 'دفتر کار با امکانات کامل',
    image: 'https://picsum.photos/seed/real23/400/300',
    hasPhoto: true,
    date: '2024-05-28',
    views: 78,
    isActive: true,
  },
  {
    id: 24,
    title: 'ویلا ۶۰۰ متری در چالوس',
    price: 15000000000,
    category: 'املاک',
    subCategory: 'فروش مسکونی',
    city: 'چالوس',
    district: 'مرکزی',
    description: 'ویلا با استخر و دریاچه',
    image: 'https://picsum.photos/seed/real24/400/300',
    hasPhoto: true,
    date: '2024-05-27',
    views: 290,
    isActive: true,
  },
  {
    id: 25,
    title: 'زمین ۱۵۰۰ متری در فردیس',
    price: 800000000,
    category: 'املاک',
    subCategory: 'زمین و باغ',
    city: 'کرج',
    district: 'فردیس',
    description: 'زمین با کاربری مسکونی',
    image: 'https://picsum.photos/seed/real25/400/300',
    hasPhoto: false,
    date: '2024-05-26',
    views: 56,
    isActive: true,
  },
  {
    id: 26,
    title: 'آپارتمان ۱۳۰ متری در پونک',
    price: 3800000000,
    category: 'املاک',
    subCategory: 'فروش مسکونی',
    city: 'تهران',
    district: 'پونک',
    description: 'آپارتمان با نمای عالی',
    image: 'https://picsum.photos/seed/real26/400/300',
    hasPhoto: true,
    date: '2024-05-25',
    views: 210,
    isActive: true,
  },
  {
    id: 27,
    title: 'مغازه ۴۵ متری در جمهوری',
    price: 2200000000,
    category: 'املاک',
    subCategory: 'فروش اداری و تجاری',
    city: 'تهران',
    district: 'جمهوری',
    description: 'مغازه با موقعیت عالی',
    image: 'https://picsum.photos/seed/real27/400/300',
    hasPhoto: true,
    date: '2024-05-24',
    views: 145,
    isActive: true,
  },
  {
    id: 28,
    title: 'زمین ۲۵۰۰ متری در فشم',
    price: 18000000000,
    category: 'املاک',
    subCategory: 'زمین و باغ',
    city: 'تهران',
    district: 'فشم',
    description: 'زمین با کاربری ویلایی',
    image: 'https://picsum.photos/seed/real28/400/300',
    hasPhoto: true,
    date: '2024-05-23',
    views: 34,
    isActive: true,
  },
  {
    id: 29,
    title: 'آپارتمان ۸۵ متری در جنت‌آباد',
    price: 2100000000,
    category: 'املاک',
    subCategory: 'فروش مسکونی',
    city: 'تهران',
    district: 'جنت‌آباد',
    description: 'آپارتمان با امکانات کامل',
    image: 'https://picsum.photos/seed/real29/400/300',
    hasPhoto: true,
    date: '2024-05-22',
    views: 178,
    isActive: true,
  },
  {
    id: 30,
    title: 'دفتر کار ۹۰ متری در خیابان انقلاب',
    price: 2800000000,
    category: 'املاک',
    subCategory: 'فروش اداری و تجاری',
    city: 'تهران',
    district: 'انقلاب',
    description: 'دفتر کار با امکانات کامل',
    image: 'https://picsum.photos/seed/real30/400/300',
    hasPhoto: false,
    date: '2024-05-21',
    views: 67,
    isActive: true,
  },
  {
    id: 31,
    title: 'ویلا ۳۵۰ متری در رشت',
    price: 3500000000,
    category: 'املاک',
    subCategory: 'فروش مسکونی',
    city: 'رشت',
    district: 'مرکزی',
    description: 'ویلا با باغچه بزرگ',
    image: 'https://picsum.photos/seed/real31/400/300',
    hasPhoto: true,
    date: '2024-05-20',
    views: 89,
    isActive: true,
  },
  {
    id: 32,
    title: 'آپارتمان ۹۵ متری در اصفهان',
    price: 1900000000,
    category: 'املاک',
    subCategory: 'فروش مسکونی',
    city: 'اصفهان',
    district: 'نقش جهان',
    description: 'آپارتمان با نمای تاریخی',
    image: 'https://picsum.photos/seed/real32/400/300',
    hasPhoto: true,
    date: '2024-05-19',
    views: 156,
    isActive: true,
  },
  {
    id: 33,
    title: 'مغازه ۳۵ متری در خیابان ولیعصر',
    price: 3000000000,
    category: 'املاک',
    subCategory: 'فروش اداری و تجاری',
    city: 'تهران',
    district: 'ولیعصر',
    description: 'مغازه با موقعیت عالی',
    image: 'https://picsum.photos/seed/real33/400/300',
    hasPhoto: false,
    date: '2024-05-18',
    views: 234,
    isActive: true,
  },
  {
    id: 34,
    title: 'زمین ۴۰۰۰ متری در شهریار',
    price: 5000000000,
    category: 'املاک',
    subCategory: 'زمین و باغ',
    city: 'شهریار',
    district: 'مرکزی',
    description: 'زمین با کاربری کشاورزی',
    image: 'https://picsum.photos/seed/real34/400/300',
    hasPhoto: true,
    date: '2024-05-17',
    views: 45,
    isActive: true,
  },
  {
    id: 35,
    title: 'آپارتمان ۱۱۰ متری در ملارد',
    price: 1400000000,
    category: 'املاک',
    subCategory: 'فروش مسکونی',
    city: 'تهران',
    district: 'ملارد',
    description: 'آپارتمان با امکانات کامل',
    image: 'https://picsum.photos/seed/real35/400/300',
    hasPhoto: true,
    date: '2024-05-16',
    views: 78,
    isActive: true,
  },
  {
    id: 36,
    title: 'دفتر کار ۱۰۰ متری در ونک',
    price: 3200000000,
    category: 'املاک',
    subCategory: 'فروش اداری و تجاری',
    city: 'تهران',
    district: 'ونک',
    description: 'دفتر کار مدرن',
    image: 'https://picsum.photos/seed/real36/400/300',
    hasPhoto: true,
    date: '2024-05-15',
    views: 112,
    isActive: true,
  },
  {
    id: 37,
    title: 'ویلا ۴۵۰ متری در نوشهر',
    price: 8000000000,
    category: 'املاک',
    subCategory: 'فروش مسکونی',
    city: 'نوشهر',
    district: 'مرکزی',
    description: 'ویلا با استخر و جنگل',
    image: 'https://picsum.photos/seed/real37/400/300',
    hasPhoto: true,
    date: '2024-05-14',
    views: 234,
    isActive: true,
  },
  {
    id: 38,
    title: 'زمین ۸۰۰ متری در پردیس',
    price: 700000000,
    category: 'املاک',
    subCategory: 'زمین و باغ',
    city: 'تهران',
    district: 'پردیس',
    description: 'زمین با کاربری مسکونی',
    image: 'https://picsum.photos/seed/real38/400/300',
    hasPhoto: false,
    date: '2024-05-13',
    views: 56,
    isActive: true,
  },
  {
    id: 39,
    title: 'آپارتمان ۷۵ متری در شرق تهران',
    price: 1600000000,
    category: 'املاک',
    subCategory: 'فروش مسکونی',
    city: 'تهران',
    district: 'شرق',
    description: 'آپارتمان با امکانات کامل',
    image: 'https://picsum.photos/seed/real39/400/300',
    hasPhoto: true,
    date: '2024-05-12',
    views: 145,
    isActive: true,
  },
  {
    id: 40,
    title: 'مغازه ۲۰ متری در پاساژ',
    price: 800000000,
    category: 'املاک',
    subCategory: 'فروش اداری و تجاری',
    city: 'تهران',
    district: 'مرکزی',
    description: 'مغازه در پاساژ معروف',
    image: 'https://picsum.photos/seed/real40/400/300',
    hasPhoto: true,
    date: '2024-05-11',
    views: 189,
    isActive: true,
  },
  {
    id: 41,
    title: 'آپارتمان ۱۴۰ متری در نیاوران',
    price: 4800000000,
    category: 'املاک',
    subCategory: 'فروش مسکونی',
    city: 'تهران',
    district: 'نیاوران',
    description: 'آپارتمان لوکس با امکانات ویژه',
    image: 'https://picsum.photos/seed/real41/400/300',
    hasPhoto: true,
    date: '2024-05-10',
    views: 310,
    isActive: true,
  },
  {
    id: 42,
    title: 'زمین ۵۰۰۰ متری در رباط کریم',
    price: 3000000000,
    category: 'املاک',
    subCategory: 'زمین و باغ',
    city: 'رباط کریم',
    district: 'مرکزی',
    description: 'زمین با کاربری صنعتی',
    image: 'https://picsum.photos/seed/real42/400/300',
    hasPhoto: false,
    date: '2024-05-09',
    views: 34,
    isActive: true,
  },
  {
    id: 43,
    title: 'دفتر کار ۷۰ متری در سهروردی',
    price: 2000000000,
    category: 'املاک',
    subCategory: 'فروش اداری و تجاری',
    city: 'تهران',
    district: 'سهروردی',
    description: 'دفتر کار با امکانات کامل',
    image: 'https://picsum.photos/seed/real43/400/300',
    hasPhoto: true,
    date: '2024-05-08',
    views: 89,
    isActive: true,
  },
  {
    id: 44,
    title: 'ویلا ۲۵۰ متری در کردان',
    price: 3000000000,
    category: 'املاک',
    subCategory: 'فروش مسکونی',
    city: 'کردان',
    district: 'مرکزی',
    description: 'ویلا با باغچه بزرگ',
    image: 'https://picsum.photos/seed/real44/400/300',
    hasPhoto: true,
    date: '2024-05-07',
    views: 78,
    isActive: true,
  },
  {
    id: 45,
    title: 'آپارتمان ۶۵ متری در شهران',
    price: 1200000000,
    category: 'املاک',
    subCategory: 'فروش مسکونی',
    city: 'تهران',
    district: 'شهران',
    description: 'آپارتمان با امکانات کامل',
    image: 'https://picsum.photos/seed/real45/400/300',
    hasPhoto: true,
    date: '2024-05-06',
    views: 123,
    isActive: true,
  },
  {
    id: 46,
    title: 'مغازه ۵۵ متری در خیابان ایران',
    price: 1800000000,
    category: 'املاک',
    subCategory: 'فروش اداری و تجاری',
    city: 'تهران',
    district: 'ایران',
    description: 'مغازه با موقعیت عالی',
    image: 'https://picsum.photos/seed/real46/400/300',
    hasPhoto: false,
    date: '2024-05-05',
    views: 156,
    isActive: true,
  },
  {
    id: 47,
    title: 'زمین ۱۲۰۰ متری در هشتگرد',
    price: 500000000,
    category: 'املاک',
    subCategory: 'زمین و باغ',
    city: 'هشتگرد',
    district: 'مرکزی',
    description: 'زمین با کاربری مسکونی',
    image: 'https://picsum.photos/seed/real47/400/300',
    hasPhoto: true,
    date: '2024-05-04',
    views: 45,
    isActive: true,
  },
  {
    id: 48,
    title: 'آپارتمان ۱۰۵ متری در تهرانسر',
    price: 2400000000,
    category: 'املاک',
    subCategory: 'فروش مسکونی',
    city: 'تهران',
    district: 'تهرانسر',
    description: 'آپارتمان با امکانات کامل',
    image: 'https://picsum.photos/seed/real48/400/300',
    hasPhoto: true,
    date: '2024-05-03',
    views: 178,
    isActive: true,
  },
  {
    id: 49,
    title: 'دفتر کار ۴۰ متری در میدان ونک',
    price: 1200000000,
    category: 'املاک',
    subCategory: 'فروش اداری و تجاری',
    city: 'تهران',
    district: 'ونک',
    description: 'دفتر کار کوچک و مدرن',
    image: 'https://picsum.photos/seed/real49/400/300',
    hasPhoto: true,
    date: '2024-05-02',
    views: 67,
    isActive: true,
  },
  {
    id: 50,
    title: 'ویلا ۵۵۰ متری در رامسر',
    price: 12000000000,
    category: 'املاک',
    subCategory: 'فروش مسکونی',
    city: 'رامسر',
    district: 'مرکزی',
    description: 'ویلا با استخر و جنگل',
    image: 'https://picsum.photos/seed/real50/400/300',
    hasPhoto: true,
    date: '2024-05-01',
    views: 290,
    isActive: true,
  },

  // ===== وسایل نقلیه (50 آگهی) =====
  {
    id: 51,
    title: 'پراید ۱۳۹۵ صفر',
    price: 350000000,
    category: 'وسایل نقلیه',
    subCategory: 'خودرو',
    city: 'تهران',
    district: 'شهرک غرب',
    description: 'پراید سفید، کارکرد ۴۵۰۰۰ کیلومتر، سالم و تمیز',
    image: 'https://picsum.photos/seed/car1/400/300',
    hasPhoto: true,
    date: '2024-06-20',
    views: 567,
    isActive: true,
  },
  {
    id: 52,
    title: 'موتورسیکلت رایزن ۲۰۰',
    price: 98000000,
    category: 'وسایل نقلیه',
    subCategory: 'موتورسیکلت',
    city: 'اصفهان',
    district: 'خواجو',
    description: 'موتور کارکرد ۱۲ هزار کیلومتر، روغن و فیلتر تعویض شده',
    image: 'https://picsum.photos/seed/car2/400/300',
    hasPhoto: true,
    date: '2024-06-16',
    views: 134,
    isActive: true,
  },
  {
    id: 53,
    title: 'آریو ۱۳۹۸ دنده‌ای',
    price: 420000000,
    category: 'وسایل نقلیه',
    subCategory: 'خودرو',
    city: 'شیراز',
    district: 'معالی‌آباد',
    description: 'آریو سفید، کارکرد ۶۸۰۰۰ کیلومتر، کاملاً سالم',
    image: 'https://picsum.photos/seed/car3/400/300',
    hasPhoto: true,
    date: '2024-06-15',
    views: 298,
    isActive: true,
  },
  {
    id: 54,
    title: 'تویوتا کمری ۲۰۲۰',
    price: 1800000000,
    category: 'وسایل نقلیه',
    subCategory: 'خودرو',
    city: 'تهران',
    district: 'جردن',
    description: 'تویوتا کمری با ۳۰ هزار کیلومتر کارکرد',
    image: 'https://picsum.photos/seed/car4/400/300',
    hasPhoto: true,
    date: '2024-06-14',
    views: 890,
    isActive: true,
  },
  {
    id: 55,
    title: 'هوندا سی‌آر-وی ۲۰۲۱',
    price: 2200000000,
    category: 'وسایل نقلیه',
    subCategory: 'خودرو',
    city: 'تهران',
    district: 'ونک',
    description: 'هوندا سی‌آر-وی با ۲۰ هزار کیلومتر کارکرد',
    image: 'https://picsum.photos/seed/car5/400/300',
    hasPhoto: true,
    date: '2024-06-13',
    views: 567,
    isActive: true,
  },
  {
    id: 56,
    title: 'دنا پلاس ۱۴۰۰',
    price: 450000000,
    category: 'وسایل نقلیه',
    subCategory: 'خودرو',
    city: 'اصفهان',
    district: 'مرکزی',
    description: 'دنا پلاس با ۴۰ هزار کیلومتر کارکرد',
    image: 'https://picsum.photos/seed/car6/400/300',
    hasPhoto: true,
    date: '2024-06-12',
    views: 234,
    isActive: true,
  },
  {
    id: 57,
    title: 'موتورسیکلت هوندا ۵۰۰',
    price: 150000000,
    category: 'وسایل نقلیه',
    subCategory: 'موتورسیکلت',
    city: 'کرج',
    district: 'مهرشهر',
    description: 'هوندا ۵۰۰ با کارکرد ۵ هزار کیلومتر',
    image: 'https://picsum.photos/seed/car7/400/300',
    hasPhoto: true,
    date: '2024-06-11',
    views: 178,
    isActive: true,
  },
  {
    id: 58,
    title: 'کیا سراتو ۲۰۱۹',
    price: 1200000000,
    category: 'وسایل نقلیه',
    subCategory: 'خودرو',
    city: 'شیراز',
    district: 'معالی‌آباد',
    description: 'کیا سراتو با ۵۰ هزار کیلومتر کارکرد',
    image: 'https://picsum.photos/seed/car8/400/300',
    hasPhoto: true,
    date: '2024-06-10',
    views: 456,
    isActive: true,
  },
  {
    id: 59,
    title: 'موتورسیکلت BMW 1200',
    price: 350000000,
    category: 'وسایل نقلیه',
    subCategory: 'موتورسیکلت',
    city: 'تهران',
    district: 'سعادت‌آباد',
    description: 'موتور BMW با کارکرد ۱۰ هزار کیلومتر',
    image: 'https://picsum.photos/seed/car9/400/300',
    hasPhoto: true,
    date: '2024-06-09',
    views: 312,
    isActive: true,
  },
  {
    id: 60,
    title: 'مزدا ۳ ۲۰۲۰',
    price: 950000000,
    category: 'وسایل نقلیه',
    subCategory: 'خودرو',
    city: 'تهران',
    district: 'پاسداران',
    description: 'مزدا ۳ با ۴۵ هزار کیلومتر کارکرد',
    image: 'https://picsum.photos/seed/car10/400/300',
    hasPhoto: true,
    date: '2024-06-08',
    views: 345,
    isActive: true,
  },
  {
    id: 61,
    title: 'سمند LX ۱۴۰۰',
    price: 320000000,
    category: 'وسایل نقلیه',
    subCategory: 'خودرو',
    city: 'تهران',
    district: 'شهرک غرب',
    description: 'سمند LX با ۶۰ هزار کیلومتر کارکرد',
    image: 'https://picsum.photos/seed/car11/400/300',
    hasPhoto: true,
    date: '2024-06-07',
    views: 189,
    isActive: true,
  },
  {
    id: 62,
    title: 'موتورسیکلت یاماها ۲۵۰',
    price: 85000000,
    category: 'وسایل نقلیه',
    subCategory: 'موتورسیکلت',
    city: 'اصفهان',
    district: 'خواجو',
    description: 'یاماها ۲۵۰ با کارکرد ۸ هزار کیلومتر',
    image: 'https://picsum.photos/seed/car12/400/300',
    hasPhoto: true,
    date: '2024-06-06',
    views: 156,
    isActive: true,
  },
  {
    id: 63,
    title: 'نیسان قشقایی ۲۰۲۱',
    price: 2000000000,
    category: 'وسایل نقلیه',
    subCategory: 'خودرو',
    city: 'تهران',
    district: 'ونک',
    description: 'نیسان قشقایی با ۳۵ هزار کیلومتر کارکرد',
    image: 'https://picsum.photos/seed/car13/400/300',
    hasPhoto: true,
    date: '2024-06-05',
    views: 678,
    isActive: true,
  },
  {
    id: 64,
    title: 'موتورسیکلت سوزوکی ۲۰۰',
    price: 70000000,
    category: 'وسایل نقلیه',
    subCategory: 'موتورسیکلت',
    city: 'کرج',
    district: 'گوهردشت',
    description: 'سوزوکی ۲۰۰ با کارکرد ۵ هزار کیلومتر',
    image: 'https://picsum.photos/seed/car14/400/300',
    hasPhoto: false,
    date: '2024-06-04',
    views: 89,
    isActive: true,
  },
  {
    id: 65,
    title: 'هیوندای النترا ۲۰۱۸',
    price: 800000000,
    category: 'وسایل نقلیه',
    subCategory: 'خودرو',
    city: 'شیراز',
    district: 'معالی‌آباد',
    description: 'هیوندای النترا با ۶۵ هزار کیلومتر کارکرد',
    image: 'https://picsum.photos/seed/car15/400/300',
    hasPhoto: true,
    date: '2024-06-03',
    views: 234,
    isActive: true,
  },
  {
    id: 66,
    title: 'پژو ۲۰۷ اتومات ۱۴۰۰',
    price: 550000000,
    category: 'وسایل نقلیه',
    subCategory: 'خودرو',
    city: 'تهران',
    district: 'جردن',
    description: 'پژو ۲۰۷ اتومات با ۳۰ هزار کیلومتر کارکرد',
    image: 'https://picsum.photos/seed/car16/400/300',
    hasPhoto: true,
    date: '2024-06-02',
    views: 456,
    isActive: true,
  },
  {
    id: 67,
    title: 'موتورسیکلت دوو ۱۵۰',
    price: 45000000,
    category: 'وسایل نقلیه',
    subCategory: 'موتورسیکلت',
    city: 'اصفهان',
    district: 'مرکزی',
    description: 'دوو ۱۵۰ با کارکرد ۱۲ هزار کیلومتر',
    image: 'https://picsum.photos/seed/car17/400/300',
    hasPhoto: false,
    date: '2024-06-01',
    views: 67,
    isActive: true,
  },
  {
    id: 68,
    title: 'فولکس واگن گلف ۲۰۲۰',
    price: 1600000000,
    category: 'وسایل نقلیه',
    subCategory: 'خودرو',
    city: 'تهران',
    district: 'پاسداران',
    description: 'فولکس واگن گلف با ۴۰ هزار کیلومتر کارکرد',
    image: 'https://picsum.photos/seed/car18/400/300',
    hasPhoto: true,
    date: '2024-05-30',
    views: 789,
    isActive: true,
  },
  {
    id: 69,
    title: 'ام‌وی‌ام ۳۱۵ ۱۴۰۰',
    price: 300000000,
    category: 'وسایل نقلیه',
    subCategory: 'خودرو',
    city: 'تهران',
    district: 'شهران',
    description: 'ام‌وی‌ام ۳۱۵ با ۵۰ هزار کیلومتر کارکرد',
    image: 'https://picsum.photos/seed/car19/400/300',
    hasPhoto: true,
    date: '2024-05-29',
    views: 145,
    isActive: true,
  },
  {
    id: 70,
    title: 'موتورسیکلت کاوازاکی ۴۰۰',
    price: 120000000,
    category: 'وسایل نقلیه',
    subCategory: 'موتورسیکلت',
    city: 'کرج',
    district: 'فردیس',
    description: 'کاوازاکی ۴۰۰ با کارکرد ۶ هزار کیلومتر',
    image: 'https://picsum.photos/seed/car20/400/300',
    hasPhoto: true,
    date: '2024-05-28',
    views: 123,
    isActive: true,
  },
  {
    id: 71,
    title: 'رنو ساندرو ۲۰۱۹',
    price: 600000000,
    category: 'وسایل نقلیه',
    subCategory: 'خودرو',
    city: 'تهران',
    district: 'شهرک غرب',
    description: 'رنو ساندرو با ۵۵ هزار کیلومتر کارکرد',
    image: 'https://picsum.photos/seed/car21/400/300',
    hasPhoto: true,
    date: '2024-05-27',
    views: 234,
    isActive: true,
  },
  {
    id: 72,
    title: 'موتورسیکلت هارلی ۸۸۳',
    price: 400000000,
    category: 'وسایل نقلیه',
    subCategory: 'موتورسیکلت',
    city: 'تهران',
    district: 'سعادت‌آباد',
    description: 'هارلی ۸۸۳ با کارکرد ۳ هزار کیلومتر',
    image: 'https://picsum.photos/seed/car22/400/300',
    hasPhoto: true,
    date: '2024-05-26',
    views: 345,
    isActive: true,
  },
  {
    id: 73,
    title: 'کیا استینگر ۲۰۲۰',
    price: 2500000000,
    category: 'وسایل نقلیه',
    subCategory: 'خودرو',
    city: 'تهران',
    district: 'ونک',
    description: 'کیا استینگر با ۳۰ هزار کیلومتر کارکرد',
    image: 'https://picsum.photos/seed/car23/400/300',
    hasPhoto: true,
    date: '2024-05-25',
    views: 890,
    isActive: true,
  },
  {
    id: 74,
    title: 'پژو ۴۰۵ ۱۳۹۸',
    price: 250000000,
    category: 'وسایل نقلیه',
    subCategory: 'خودرو',
    city: 'اصفهان',
    district: 'خواجو',
    description: 'پژو ۴۰۵ با ۸۰ هزار کیلومتر کارکرد',
    image: 'https://picsum.photos/seed/car24/400/300',
    hasPhoto: false,
    date: '2024-05-24',
    views: 89,
    isActive: true,
  },
  {
    id: 75,
    title: 'موتورسیکلت تریومف ۹۰۰',
    price: 250000000,
    category: 'وسایل نقلیه',
    subCategory: 'موتورسیکلت',
    city: 'شیراز',
    district: 'معالی‌آباد',
    description: 'تریومف ۹۰۰ با کارکرد ۴ هزار کیلومتر',
    image: 'https://picsum.photos/seed/car25/400/300',
    hasPhoto: true,
    date: '2024-05-23',
    views: 156,
    isActive: true,
  },
  {
    id: 76,
    title: 'تویوتا لندکروزر ۲۰۲۰',
    price: 5000000000,
    category: 'وسایل نقلیه',
    subCategory: 'خودرو',
    city: 'تهران',
    district: 'شمال',
    description: 'تویوتا لندکروزر با ۲۰ هزار کیلومتر کارکرد',
    image: 'https://picsum.photos/seed/car26/400/300',
    hasPhoto: true,
    date: '2024-05-22',
    views: 678,
    isActive: true,
  },
  {
    id: 77,
    title: 'موتورسیکلت دوکاتی ۱۲۰۰',
    price: 450000000,
    category: 'وسایل نقلیه',
    subCategory: 'موتورسیکلت',
    city: 'تهران',
    district: 'جردن',
    description: 'دوکاتی ۱۲۰۰ با کارکرد ۵ هزار کیلومتر',
    image: 'https://picsum.photos/seed/car27/400/300',
    hasPhoto: true,
    date: '2024-05-21',
    views: 234,
    isActive: true,
  },
  {
    id: 78,
    title: 'هیوندای سانتافه ۲۰۲۰',
    price: 1800000000,
    category: 'وسایل نقلیه',
    subCategory: 'خودرو',
    city: 'تهران',
    district: 'پاسداران',
    description: 'هیوندای سانتافه با ۴۰ هزار کیلومتر کارکرد',
    image: 'https://picsum.photos/seed/car28/400/300',
    hasPhoto: true,
    date: '2024-05-20',
    views: 456,
    isActive: true,
  },
  {
    id: 79,
    title: 'موتورسیکلت باجاج ۲۰۰',
    price: 30000000,
    category: 'وسایل نقلیه',
    subCategory: 'موتورسیکلت',
    city: 'کرج',
    district: 'مهرشهر',
    description: 'باجاج ۲۰۰ با کارکرد ۱۵ هزار کیلومتر',
    image: 'https://picsum.photos/seed/car29/400/300',
    hasPhoto: false,
    date: '2024-05-19',
    views: 78,
    isActive: true,
  },
  {
    id: 80,
    title: 'میتسوبیشی اوتلندر ۲۰۱۹',
    price: 1200000000,
    category: 'وسایل نقلیه',
    subCategory: 'خودرو',
    city: 'تهران',
    district: 'سعادت‌آباد',
    description: 'میتسوبیشی اوتلندر با ۵۰ هزار کیلومتر کارکرد',
    image: 'https://picsum.photos/seed/car30/400/300',
    hasPhoto: true,
    date: '2024-05-18',
    views: 345,
    isActive: true,
  },
  {
    id: 81,
    title: 'پژو پارس ۱۴۰۰',
    price: 280000000,
    category: 'وسایل نقلیه',
    subCategory: 'خودرو',
    city: 'اصفهان',
    district: 'نقش جهان',
    description: 'پژو پارس با ۶۵ هزار کیلومتر کارکرد',
    image: 'https://picsum.photos/seed/car31/400/300',
    hasPhoto: true,
    date: '2024-05-17',
    views: 189,
    isActive: true,
  },
  {
    id: 82,
    title: 'موتورسیکلت بنلی ۳۰۰',
    price: 80000000,
    category: 'وسایل نقلیه',
    subCategory: 'موتورسیکلت',
    city: 'تهران',
    district: 'شهرک غرب',
    description: 'بنلی ۳۰۰ با کارکرد ۷ هزار کیلومتر',
    image: 'https://picsum.photos/seed/car32/400/300',
    hasPhoto: true,
    date: '2024-05-16',
    views: 145,
    isActive: true,
  },
  {
    id: 83,
    title: 'ام‌جی ۵ ۲۰۲۰',
    price: 850000000,
    category: 'وسایل نقلیه',
    subCategory: 'خودرو',
    city: 'تهران',
    district: 'ونک',
    description: 'ام‌جی ۵ با ۳۵ هزار کیلومتر کارکرد',
    image: 'https://picsum.photos/seed/car33/400/300',
    hasPhoto: true,
    date: '2024-05-15',
    views: 234,
    isActive: true,
  },
  {
    id: 84,
    title: 'موتورسیکلت ولو ۱۵۰',
    price: 25000000,
    category: 'وسایل نقلیه',
    subCategory: 'موتورسیکلت',
    city: 'شیراز',
    district: 'زند',
    description: 'ولو ۱۵۰ با کارکرد ۲۰ هزار کیلومتر',
    image: 'https://picsum.photos/seed/car34/400/300',
    hasPhoto: false,
    date: '2024-05-14',
    views: 56,
    isActive: true,
  },
  {
    id: 85,
    title: 'لکسوس NX ۲۰۲۰',
    price: 2800000000,
    category: 'وسایل نقلیه',
    subCategory: 'خودرو',
    city: 'تهران',
    district: 'جردن',
    description: 'لکسوس NX با ۲۵ هزار کیلومتر کارکرد',
    image: 'https://picsum.photos/seed/car35/400/300',
    hasPhoto: true,
    date: '2024-05-13',
    views: 567,
    isActive: true,
  },
  {
    id: 86,
    title: 'موتورسیکلت آپریلیا ۷۵۰',
    price: 180000000,
    category: 'وسایل نقلیه',
    subCategory: 'موتورسیکلت',
    city: 'تهران',
    district: 'شمال',
    description: 'آپریلیا ۷۵۰ با کارکرد ۴ هزار کیلومتر',
    image: 'https://picsum.photos/seed/car36/400/300',
    hasPhoto: true,
    date: '2024-05-12',
    views: 189,
    isActive: true,
  },
  {
    id: 87,
    title: 'تویوتا کرولا ۲۰۲۰',
    price: 1500000000,
    category: 'وسایل نقلیه',
    subCategory: 'خودرو',
    city: 'اصفهان',
    district: 'مرکزی',
    description: 'تویوتا کرولا با ۴۵ هزار کیلومتر کارکرد',
    image: 'https://picsum.photos/seed/car37/400/300',
    hasPhoto: true,
    date: '2024-05-11',
    views: 345,
    isActive: true,
  },
  {
    id: 88,
    title: 'موتورسیکلت هوندا ۲۵۰',
    price: 65000000,
    category: 'وسایل نقلیه',
    subCategory: 'موتورسیکلت',
    city: 'کرج',
    district: 'گوهردشت',
    description: 'هوندا ۲۵۰ با کارکرد ۶ هزار کیلومتر',
    image: 'https://picsum.photos/seed/car38/400/300',
    hasPhoto: true,
    date: '2024-05-10',
    views: 123,
    isActive: true,
  },
  {
    id: 89,
    title: 'نیسان تایدا ۲۰۱۹',
    price: 550000000,
    category: 'وسایل نقلیه',
    subCategory: 'خودرو',
    city: 'تهران',
    district: 'شهرک غرب',
    description: 'نیسان تایدا با ۶۰ هزار کیلومتر کارکرد',
    image: 'https://picsum.photos/seed/car39/400/300',
    hasPhoto: true,
    date: '2024-05-09',
    views: 156,
    isActive: true,
  },
  {
    id: 90,
    title: 'موتورسیکلت جی‌ت ۳۰۰',
    price: 90000000,
    category: 'وسایل نقلیه',
    subCategory: 'موتورسیکلت',
    city: 'تهران',
    district: 'پاسداران',
    description: 'جی‌ت ۳۰۰ با کارکرد ۵ هزار کیلومتر',
    image: 'https://picsum.photos/seed/car40/400/300',
    hasPhoto: false,
    date: '2024-05-08',
    views: 89,
    isActive: true,
  },
  {
    id: 91,
    title: 'رنج‌روور ولار ۲۰۲۰',
    price: 3500000000,
    category: 'وسایل نقلیه',
    subCategory: 'خودرو',
    city: 'تهران',
    district: 'سعادت‌آباد',
    description: 'رنج‌روور ولار با ۲۰ هزار کیلومتر کارکرد',
    image: 'https://picsum.photos/seed/car41/400/300',
    hasPhoto: true,
    date: '2024-05-07',
    views: 456,
    isActive: true,
  },
  {
    id: 92,
    title: 'موتورسیکلت داف ۲۰۰',
    price: 55000000,
    category: 'وسایل نقلیه',
    subCategory: 'موتورسیکلت',
    city: 'اصفهان',
    district: 'خواجو',
    description: 'داف ۲۰۰ با کارکرد ۹ هزار کیلومتر',
    image: 'https://picsum.photos/seed/car42/400/300',
    hasPhoto: true,
    date: '2024-05-06',
    views: 78,
    isActive: true,
  },
  {
    id: 93,
    title: 'مزدا ۶ ۲۰۲۰',
    price: 1400000000,
    category: 'وسایل نقلیه',
    subCategory: 'خودرو',
    city: 'تهران',
    district: 'ونک',
    description: 'مزدا ۶ با ۳۰ هزار کیلومتر کارکرد',
    image: 'https://picsum.photos/seed/car43/400/300',
    hasPhoto: true,
    date: '2024-05-05',
    views: 234,
    isActive: true,
  },
  {
    id: 94,
    title: 'موتورسیکلت شاین ۱۵۰',
    price: 20000000,
    category: 'وسایل نقلیه',
    subCategory: 'موتورسیکلت',
    city: 'شیراز',
    district: 'معالی‌آباد',
    description: 'شاین ۱۵۰ با کارکرد ۱۸ هزار کیلومتر',
    image: 'https://picsum.photos/seed/car44/400/300',
    hasPhoto: false,
    date: '2024-05-04',
    views: 45,
    isActive: true,
  },
  {
    id: 95,
    title: 'جیپ گرند چروکی ۲۰۲۰',
    price: 4500000000,
    category: 'وسایل نقلیه',
    subCategory: 'خودرو',
    city: 'تهران',
    district: 'شمال',
    description: 'جیپ گرند چروکی با ۱۵ هزار کیلومتر کارکرد',
    image: 'https://picsum.photos/seed/car45/400/300',
    hasPhoto: true,
    date: '2024-05-03',
    views: 567,
    isActive: true,
  },
  {
    id: 96,
    title: 'موتورسیکلت کاسپین ۲۰۰',
    price: 40000000,
    category: 'وسایل نقلیه',
    subCategory: 'موتورسیکلت',
    city: 'کرج',
    district: 'مهرشهر',
    description: 'کاسپین ۲۰۰ با کارکرد ۱۲ هزار کیلومتر',
    image: 'https://picsum.photos/seed/car46/400/300',
    hasPhoto: true,
    date: '2024-05-02',
    views: 67,
    isActive: true,
  },
  {
    id: 97,
    title: 'فولکس واگن پاسات ۲۰۲۰',
    price: 2200000000,
    category: 'وسایل نقلیه',
    subCategory: 'خودرو',
    city: 'تهران',
    district: 'جردن',
    description: 'فولکس واگن پاسات با ۲۵ هزار کیلومتر کارکرد',
    image: 'https://picsum.photos/seed/car47/400/300',
    hasPhoto: true,
    date: '2024-05-01',
    views: 345,
    isActive: true,
  },
  {
    id: 98,
    title: 'موتورسیکلت دوشنبه ۱۵۰',
    price: 15000000,
    category: 'وسایل نقلیه',
    subCategory: 'موتورسیکلت',
    city: 'اصفهان',
    district: 'نقش جهان',
    description: 'دوشنبه ۱۵۰ با کارکرد ۲۲ هزار کیلومتر',
    image: 'https://picsum.photos/seed/car48/400/300',
    hasPhoto: false,
    date: '2024-04-30',
    views: 34,
    isActive: true,
  },
  {
    id: 99,
    title: 'کیا اپتیما ۲۰۲۰',
    price: 1600000000,
    category: 'وسایل نقلیه',
    subCategory: 'خودرو',
    city: 'تهران',
    district: 'پاسداران',
    description: 'کیا اپتیما با ۴۰ هزار کیلومتر کارکرد',
    image: 'https://picsum.photos/seed/car49/400/300',
    hasPhoto: true,
    date: '2024-04-29',
    views: 456,
    isActive: true,
  },
  {
    id: 100,
    title: 'موتورسیکلت بی‌ام‌دبلیو ۸۰۰',
    price: 300000000,
    category: 'وسایل نقلیه',
    subCategory: 'موتورسیکلت',
    city: 'تهران',
    district: 'سعادت‌آباد',
    description: 'بی‌ام‌دبلیو ۸۰۰ با کارکرد ۳ هزار کیلومتر',
    image: 'https://picsum.photos/seed/car50/400/300',
    hasPhoto: true,
    date: '2024-04-28',
    views: 234,
    isActive: true,
  },

  // ===== کالای دیجیتال (50 آگهی) =====
  {
    id: 101,
    title: 'آیفون ۱۴ پرو مکس ۲۵۶',
    price: 65000000,
    category: 'کالای دیجیتال',
    subCategory: 'موبایل و تبلت',
    city: 'تهران',
    district: 'ونک',
    description: 'گوشی دربسته، گارانتی ۱۸ ماهه، فاکتور دارد',
    image: 'https://picsum.photos/seed/digital1/400/300',
    hasPhoto: true,
    date: '2024-06-20',
    views: 890,
    isActive: true,
  },
  {
    id: 102,
    title: 'لپ‌تاپ ایسوس زن‌بوک',
    price: 28000000,
    category: 'کالای دیجیتال',
    subCategory: 'رایانه',
    city: 'تهران',
    district: 'پاسداران',
    description: 'لپ‌تاپ با رم ۱۶ گیگ، SSD 512، کور i7 نسل ۱۱',
    image: 'https://picsum.photos/seed/digital2/400/300',
    hasPhoto: true,
    date: '2024-06-18',
    views: 156,
    isActive: true,
  },
  {
    id: 103,
    title: 'هدفون سونی WH-1000XM4',
    price: 8500000,
    category: 'کالای دیجیتال',
    subCategory: 'لوازم جانبی',
    city: 'اصفهان',
    district: 'چهارباغ',
    description: 'نو، دربسته، فاقد کالا، گارانتی ۲ ساله',
    image: 'https://picsum.photos/seed/digital3/400/300',
    hasPhoto: true,
    date: '2024-06-14',
    views: 203,
    isActive: true,
  },
  {
    id: 104,
    title: 'سامسونگ گلکسی اس۲۴ اولترا',
    price: 75000000,
    category: 'کالای دیجیتال',
    subCategory: 'موبایل و تبلت',
    city: 'تهران',
    district: 'جردن',
    description: 'گوشی دربسته، گارانتی ۲ ساله',
    image: 'https://picsum.photos/seed/digital4/400/300',
    hasPhoto: true,
    date: '2024-06-17',
    views: 1200,
    isActive: true,
  },
  {
    id: 105,
    title: 'مک‌بوک پرو M3',
    price: 85000000,
    category: 'کالای دیجیتال',
    subCategory: 'رایانه',
    city: 'تهران',
    district: 'سعادت‌آباد',
    description: 'مک‌بوک پرو با رم ۱۶ گیگ، SSD 1TB',
    image: 'https://picsum.photos/seed/digital5/400/300',
    hasPhoto: true,
    date: '2024-06-16',
    views: 567,
    isActive: true,
  },
  {
    id: 106,
    title: 'دوربین کانن EOS R5',
    price: 120000000,
    category: 'کالای دیجیتال',
    subCategory: 'صوتی و تصویری',
    city: 'اصفهان',
    district: 'مرکزی',
    description: 'دوربین حرفه‌ای با لنز کیت',
    image: 'https://picsum.photos/seed/digital6/400/300',
    hasPhoto: true,
    date: '2024-06-15',
    views: 345,
    isActive: true,
  },
  {
    id: 107,
    title: 'گوشی گوگل پیکسل ۸ پرو',
    price: 60000000,
    category: 'کالای دیجیتال',
    subCategory: 'موبایل و تبلت',
    city: 'تهران',
    district: 'پاسداران',
    description: 'گوشی با دوربین عالی و گارانتی ۱ ساله',
    image: 'https://picsum.photos/seed/digital7/400/300',
    hasPhoto: true,
    date: '2024-06-14',
    views: 456,
    isActive: true,
  },
  {
    id: 108,
    title: 'لپ‌تاپ لنوو ThinkPad X1',
    price: 38000000,
    category: 'کالای دیجیتال',
    subCategory: 'رایانه',
    city: 'شیراز',
    district: 'معالی‌آباد',
    description: 'لپ‌تاپ با رم ۳۲ گیگ، SSD 512',
    image: 'https://picsum.photos/seed/digital8/400/300',
    hasPhoto: true,
    date: '2024-06-13',
    views: 234,
    isActive: true,
  },
  {
    id: 109,
    title: 'اپل واچ سری ۹',
    price: 25000000,
    category: 'کالای دیجیتال',
    subCategory: 'لوازم جانبی',
    city: 'تهران',
    district: 'ونک',
    description: 'ساعت هوشمند با گارانتی ۱ ساله',
    image: 'https://picsum.photos/seed/digital9/400/300',
    hasPhoto: true,
    date: '2024-06-12',
    views: 678,
    isActive: true,
  },
  {
    id: 110,
    title: 'هدفون بی‌س بوست ۳',
    price: 4500000,
    category: 'کالای دیجیتال',
    subCategory: 'لوازم جانبی',
    city: 'تهران',
    district: 'شهرک غرب',
    description: 'هدفون بی‌س با گارانتی ۱ ساله',
    image: 'https://picsum.photos/seed/digital10/400/300',
    hasPhoto: false,
    date: '2024-06-11',
    views: 189,
    isActive: true,
  },
  {
    id: 111,
    title: 'سامسونگ گلکسی بوک ۴',
    price: 40000000,
    category: 'کالای دیجیتال',
    subCategory: 'رایانه',
    city: 'کرج',
    district: 'مهرشهر',
    description: 'لپ‌تاپ با رم ۱۶ گیگ، SSD 512',
    image: 'https://picsum.photos/seed/digital11/400/300',
    hasPhoto: true,
    date: '2024-06-10',
    views: 156,
    isActive: true,
  },
  {
    id: 112,
    title: 'دوربین سونی A7 IV',
    price: 100000000,
    category: 'کالای دیجیتال',
    subCategory: 'صوتی و تصویری',
    city: 'تهران',
    district: 'جردن',
    description: 'دوربین حرفه‌ای با گارانتی ۲ ساله',
    image: 'https://picsum.photos/seed/digital12/400/300',
    hasPhoto: true,
    date: '2024-06-09',
    views: 456,
    isActive: true,
  },
  {
    id: 113,
    title: 'گوشی شیائومی ۱۴ پرو',
    price: 40000000,
    category: 'کالای دیجیتال',
    subCategory: 'موبایل و تبلت',
    city: 'تهران',
    district: 'پاسداران',
    description: 'گوشی با دوربین ۲۰۰ مگاپیکسلی',
    image: 'https://picsum.photos/seed/digital13/400/300',
    hasPhoto: true,
    date: '2024-06-08',
    views: 345,
    isActive: true,
  },
  {
    id: 114,
    title: 'لپ‌تاپ اچ‌پی Spectre x360',
    price: 45000000,
    category: 'کالای دیجیتال',
    subCategory: 'رایانه',
    city: 'اصفهان',
    district: 'نقش جهان',
    description: 'لپ‌تاپ با صفحه لمسی و قلم',
    image: 'https://picsum.photos/seed/digital14/400/300',
    hasPhoto: false,
    date: '2024-06-07',
    views: 123,
    isActive: true,
  },
  {
    id: 115,
    title: 'هدفون سونی WH-1000XM5',
    price: 12000000,
    category: 'کالای دیجیتال',
    subCategory: 'لوازم جانبی',
    city: 'تهران',
    district: 'سعادت‌آباد',
    description: 'هدفون با نویز کنسلینگ عالی',
    image: 'https://picsum.photos/seed/digital15/400/300',
    hasPhoto: true,
    date: '2024-06-06',
    views: 234,
    isActive: true,
  },
  {
    id: 116,
    title: 'گوشی آنر میجیک ۶ پرو',
    price: 45000000,
    category: 'کالای دیجیتال',
    subCategory: 'موبایل و تبلت',
    city: 'شیراز',
    district: 'زند',
    description: 'گوشی با دوربین پریسکوپی',
    image: 'https://picsum.photos/seed/digital16/400/300',
    hasPhoto: true,
    date: '2024-06-05',
    views: 345,
    isActive: true,
  },
  {
    id: 117,
    title: 'لپ‌تاپ ایسر Swift 5',
    price: 22000000,
    category: 'کالای دیجیتال',
    subCategory: 'رایانه',
    city: 'تهران',
    district: 'شهرک غرب',
    description: 'لپ‌تاپ سبک با رم ۱۶ گیگ',
    image: 'https://picsum.photos/seed/digital17/400/300',
    hasPhoto: false,
    date: '2024-06-04',
    views: 89,
    isActive: true,
  },
  {
    id: 118,
    title: 'دوربین نیکون Z8',
    price: 150000000,
    category: 'کالای دیجیتال',
    subCategory: 'صوتی و تصویری',
    city: 'تهران',
    district: 'ونک',
    description: 'دوربین حرفه‌ای با گارانتی ۳ ساله',
    image: 'https://picsum.photos/seed/digital18/400/300',
    hasPhoto: true,
    date: '2024-06-03',
    views: 567,
    isActive: true,
  },
  {
    id: 119,
    title: 'گوشی ناتینگ فون ۲',
    price: 30000000,
    category: 'کالای دیجیتال',
    subCategory: 'موبایل و تبلت',
    city: 'تهران',
    district: 'جردن',
    description: 'گوشی با طراحی خاص',
    image: 'https://picsum.photos/seed/digital19/400/300',
    hasPhoto: true,
    date: '2024-06-02',
    views: 234,
    isActive: true,
  },
  {
    id: 120,
    title: 'هدفون جی‌بی‌ال ۷۵۰',
    price: 3500000,
    category: 'کالای دیجیتال',
    subCategory: 'لوازم جانبی',
    city: 'اصفهان',
    district: 'چهارباغ',
    description: 'هدفون با صدای عالی',
    image: 'https://picsum.photos/seed/digital20/400/300',
    hasPhoto: false,
    date: '2024-06-01',
    views: 156,
    isActive: true,
  },
  {
    id: 121,
    title: 'لپ‌تاپ دل XPS 15',
    price: 55000000,
    category: 'کالای دیجیتال',
    subCategory: 'رایانه',
    city: 'تهران',
    district: 'پاسداران',
    description: 'لپ‌تاپ با صفحه OLED',
    image: 'https://picsum.photos/seed/digital21/400/300',
    hasPhoto: true,
    date: '2024-05-30',
    views: 345,
    isActive: true,
  },
  {
    id: 122,
    title: 'گوشی وان‌پلاس ۱۲',
    price: 50000000,
    category: 'کالای دیجیتال',
    subCategory: 'موبایل و تبلت',
    city: 'تهران',
    district: 'سعادت‌آباد',
    description: 'گوشی با شارژ سریع ۱۰۰ وات',
    image: 'https://picsum.photos/seed/digital22/400/300',
    hasPhoto: true,
    date: '2024-05-29',
    views: 456,
    isActive: true,
  },
  {
    id: 123,
    title: 'دوربین گوپرو هیرو ۱۲',
    price: 25000000,
    category: 'کالای دیجیتال',
    subCategory: 'صوتی و تصویری',
    city: 'کرج',
    district: 'مهرشهر',
    description: 'دوربین ورزشی با گارانتی ۱ ساله',
    image: 'https://picsum.photos/seed/digital23/400/300',
    hasPhoto: true,
    date: '2024-05-28',
    views: 234,
    isActive: true,
  },
  {
    id: 124,
    title: 'لپ‌تاپ اسوس ROG Zephyrus',
    price: 70000000,
    category: 'کالای دیجیتال',
    subCategory: 'رایانه',
    city: 'تهران',
    district: 'ونک',
    description: 'لپ‌تاپ گیمینگ با کارت گرافیک RTX',
    image: 'https://picsum.photos/seed/digital24/400/300',
    hasPhoto: true,
    date: '2024-05-27',
    views: 890,
    isActive: true,
  },
  {
    id: 125,
    title: 'هدفون اپل ایرپادز پرو ۲',
    price: 15000000,
    category: 'کالای دیجیتال',
    subCategory: 'لوازم جانبی',
    city: 'تهران',
    district: 'شهرک غرب',
    description: 'ایرپادز با نویز کنسلینگ',
    image: 'https://picsum.photos/seed/digital25/400/300',
    hasPhoto: true,
    date: '2024-05-26',
    views: 567,
    isActive: true,
  },
  {
    id: 126,
    title: 'گوشی سامسونگ گلکسی A55',
    price: 25000000,
    category: 'کالای دیجیتال',
    subCategory: 'موبایل و تبلت',
    city: 'اصفهان',
    district: 'مرکزی',
    description: 'گوشی میان‌رده با گارانتی ۲ ساله',
    image: 'https://picsum.photos/seed/digital26/400/300',
    hasPhoto: true,
    date: '2024-05-25',
    views: 234,
    isActive: true,
  },
  {
    id: 127,
    title: 'لپ‌تاپ مک‌بوک ایر M1',
    price: 45000000,
    category: 'کالای دیجیتال',
    subCategory: 'رایانه',
    city: 'شیراز',
    district: 'معالی‌آباد',
    description: 'لپ‌تاپ سبک با گارانتی ۱ ساله',
    image: 'https://picsum.photos/seed/digital27/400/300',
    hasPhoto: false,
    date: '2024-05-24',
    views: 345,
    isActive: true,
  },
  {
    id: 128,
    title: 'دوربین سونی ZV-E10',
    price: 35000000,
    category: 'کالای دیجیتال',
    subCategory: 'صوتی و تصویری',
    city: 'تهران',
    district: 'جردن',
    description: 'دوربین مخصوص ولاگرها',
    image: 'https://picsum.photos/seed/digital28/400/300',
    hasPhoto: true,
    date: '2024-05-23',
    views: 456,
    isActive: true,
  },
  {
    id: 129,
    title: 'گوشی موتورولا اج ۵۰',
    price: 35000000,
    category: 'کالای دیجیتال',
    subCategory: 'موبایل و تبلت',
    city: 'تهران',
    district: 'پاسداران',
    description: 'گوشی با صفحه خمیده',
    image: 'https://picsum.photos/seed/digital29/400/300',
    hasPhoto: true,
    date: '2024-05-22',
    views: 234,
    isActive: true,
  },
  {
    id: 130,
    title: 'هدفون سامسونگ گلکسی بادز ۳',
    price: 8000000,
    category: 'کالای دیجیتال',
    subCategory: 'لوازم جانبی',
    city: 'تهران',
    district: 'سعادت‌آباد',
    description: 'هدفون با گارانتی ۱ ساله',
    image: 'https://picsum.photos/seed/digital30/400/300',
    hasPhoto: false,
    date: '2024-05-21',
    views: 189,
    isActive: true,
  },
  {
    id: 131,
    title: 'لپ‌تاپ اچ‌پی Pavilion 15',
    price: 20000000,
    category: 'کالای دیجیتال',
    subCategory: 'رایانه',
    city: 'کرج',
    district: 'گوهردشت',
    description: 'لپ‌تاپ با گارانتی ۲ ساله',
    image: 'https://picsum.photos/seed/digital31/400/300',
    hasPhoto: true,
    date: '2024-05-20',
    views: 156,
    isActive: true,
  },
  {
    id: 132,
    title: 'دوربین کانن EOS 200D',
    price: 25000000,
    category: 'کالای دیجیتال',
    subCategory: 'صوتی و تصویری',
    city: 'اصفهان',
    district: 'خواجو',
    description: 'دوربین با لنز کیت',
    image: 'https://picsum.photos/seed/digital32/400/300',
    hasPhoto: true,
    date: '2024-05-19',
    views: 234,
    isActive: true,
  },
  {
    id: 133,
    title: 'گوشی آنر X9b',
    price: 18000000,
    category: 'کالای دیجیتال',
    subCategory: 'موبایل و تبلت',
    city: 'تهران',
    district: 'شهرک غرب',
    description: 'گوشی با دوربین ۱۰۰ مگاپیکسلی',
    image: 'https://picsum.photos/seed/digital33/400/300',
    hasPhoto: true,
    date: '2024-05-18',
    views: 345,
    isActive: true,
  },
  {
    id: 134,
    title: 'لپ‌تاپ لنوو IdeaPad 5',
    price: 28000000,
    category: 'کالای دیجیتال',
    subCategory: 'رایانه',
    city: 'شیراز',
    district: 'زند',
    description: 'لپ‌تاپ با گارانتی ۱ ساله',
    image: 'https://picsum.photos/seed/digital34/400/300',
    hasPhoto: false,
    date: '2024-05-17',
    views: 89,
    isActive: true,
  },
  {
    id: 135,
    title: 'هدفون جی‌بی‌ال Tune 770',
    price: 3000000,
    category: 'کالای دیجیتال',
    subCategory: 'لوازم جانبی',
    city: 'تهران',
    district: 'ونک',
    description: 'هدفون با صدای عالی',
    image: 'https://picsum.photos/seed/digital35/400/300',
    hasPhoto: true,
    date: '2024-05-16',
    views: 123,
    isActive: true,
  },
  {
    id: 136,
    title: 'گوشی سامسونگ گلکسی S23 FE',
    price: 35000000,
    category: 'کالای دیجیتال',
    subCategory: 'موبایل و تبلت',
    city: 'تهران',
    district: 'جردن',
    description: 'گوشی با گارانتی ۲ ساله',
    image: 'https://picsum.photos/seed/digital36/400/300',
    hasPhoto: true,
    date: '2024-05-15',
    views: 456,
    isActive: true,
  },
  {
    id: 137,
    title: 'لپ‌تاپ اسوس Vivobook 16',
    price: 25000000,
    category: 'کالای دیجیتال',
    subCategory: 'رایانه',
    city: 'اصفهان',
    district: 'نقش جهان',
    description: 'لپ‌تاپ با گارانتی ۱ ساله',
    image: 'https://picsum.photos/seed/digital37/400/300',
    hasPhoto: true,
    date: '2024-05-14',
    views: 234,
    isActive: true,
  },
  {
    id: 138,
    title: 'دوربین پاناسونیک Lumix S5',
    price: 80000000,
    category: 'کالای دیجیتال',
    subCategory: 'صوتی و تصویری',
    city: 'تهران',
    district: 'پاسداران',
    description: 'دوربین حرفه‌ای با گارانتی ۲ ساله',
    image: 'https://picsum.photos/seed/digital38/400/300',
    hasPhoto: true,
    date: '2024-05-13',
    views: 345,
    isActive: true,
  },
  {
    id: 139,
    title: 'گوشی شیائومی 14T',
    price: 28000000,
    category: 'کالای دیجیتال',
    subCategory: 'موبایل و تبلت',
    city: 'تهران',
    district: 'سعادت‌آباد',
    description: 'گوشی با گارانتی ۱ ساله',
    image: 'https://picsum.photos/seed/digital39/400/300',
    hasPhoto: false,
    date: '2024-05-12',
    views: 189,
    isActive: true,
  },
  {
    id: 140,
    title: 'هدفون سونی WH-CH720N',
    price: 6000000,
    category: 'کالای دیجیتال',
    subCategory: 'لوازم جانبی',
    city: 'کرج',
    district: 'مهرشهر',
    description: 'هدفون با نویز کنسلینگ',
    image: 'https://picsum.photos/seed/digital40/400/300',
    hasPhoto: true,
    date: '2024-05-11',
    views: 156,
    isActive: true,
  },
  {
    id: 141,
    title: 'لپ‌تاپ دل Latitude 5430',
    price: 32000000,
    category: 'کالای دیجیتال',
    subCategory: 'رایانه',
    city: 'تهران',
    district: 'شهرک غرب',
    description: 'لپ‌تاپ با گارانتی ۲ ساله',
    image: 'https://picsum.photos/seed/digital41/400/300',
    hasPhoto: true,
    date: '2024-05-10',
    views: 234,
    isActive: true,
  },
  {
    id: 142,
    title: 'گوشی گوگل پیکسل 7a',
    price: 20000000,
    category: 'کالای دیجیتال',
    subCategory: 'موبایل و تبلت',
    city: 'اصفهان',
    district: 'چهارباغ',
    description: 'گوشی با دوربین عالی',
    image: 'https://picsum.photos/seed/digital42/400/300',
    hasPhoto: true,
    date: '2024-05-09',
    views: 345,
    isActive: true,
  },
  {
    id: 143,
    title: 'هدفون بوز QC45',
    price: 10000000,
    category: 'کالای دیجیتال',
    subCategory: 'لوازم جانبی',
    city: 'تهران',
    district: 'ونک',
    description: 'هدفون با نویز کنسلینگ عالی',
    image: 'https://picsum.photos/seed/digital43/400/300',
    hasPhoto: false,
    date: '2024-05-08',
    views: 189,
    isActive: true,
  },
  {
    id: 144,
    title: 'گوشی هوآوی P60 Pro',
    price: 55000000,
    category: 'کالای دیجیتال',
    subCategory: 'موبایل و تبلت',
    city: 'تهران',
    district: 'جردن',
    description: 'گوشی با دوربین پریسکوپی',
    image: 'https://picsum.photos/seed/digital44/400/300',
    hasPhoto: true,
    date: '2024-05-07',
    views: 567,
    isActive: true,
  },
  {
    id: 145,
    title: 'لپ‌تاپ ایسوس TUF Gaming',
    price: 45000000,
    category: 'کالای دیجیتال',
    subCategory: 'رایانه',
    city: 'شیراز',
    district: 'معالی‌آباد',
    description: 'لپ‌تاپ گیمینگ با گارانتی ۲ ساله',
    image: 'https://picsum.photos/seed/digital45/400/300',
    hasPhoto: true,
    date: '2024-05-06',
    views: 456,
    isActive: true,
  },
  {
    id: 146,
    title: 'دوربین فوجی‌فیلم X-T5',
    price: 95000000,
    category: 'کالای دیجیتال',
    subCategory: 'صوتی و تصویری',
    city: 'تهران',
    district: 'پاسداران',
    description: 'دوربین حرفه‌ای با گارانتی ۲ ساله',
    image: 'https://picsum.photos/seed/digital46/400/300',
    hasPhoto: true,
    date: '2024-05-05',
    views: 678,
    isActive: true,
  },
  {
    id: 147,
    title: 'گوشی نوکیا XR21',
    price: 15000000,
    category: 'کالای دیجیتال',
    subCategory: 'موبایل و تبلت',
    city: 'تهران',
    district: 'سعادت‌آباد',
    description: 'گوشی ضد آب با گارانتی ۱ ساله',
    image: 'https://picsum.photos/seed/digital47/400/300',
    hasPhoto: false,
    date: '2024-05-04',
    views: 123,
    isActive: true,
  },
  {
    id: 148,
    title: 'هدفون سامسونگ گلکسی بادز ۲',
    price: 5000000,
    category: 'کالای دیجیتال',
    subCategory: 'لوازم جانبی',
    city: 'اصفهان',
    district: 'مرکزی',
    description: 'هدفون با گارانتی ۱ ساله',
    image: 'https://picsum.photos/seed/digital48/400/300',
    hasPhoto: true,
    date: '2024-05-03',
    views: 234,
    isActive: true,
  },
  {
    id: 149,
    title: 'لپ‌تاپ مک‌بوک پرو ۱۶ اینچ',
    price: 95000000,
    category: 'کالای دیجیتال',
    subCategory: 'رایانه',
    city: 'تهران',
    district: 'ونک',
    description: 'لپ‌تاپ با صفحه بزرگ و گارانتی ۲ ساله',
    image: 'https://picsum.photos/seed/digital49/400/300',
    hasPhoto: true,
    date: '2024-05-02',
    views: 789,
    isActive: true,
  },
  {
    id: 150,
    title: 'گوشی آنر مجیک V2',
    price: 65000000,
    category: 'کالای دیجیتال',
    subCategory: 'موبایل و تبلت',
    city: 'تهران',
    district: 'جردن',
    description: 'گوشی تاشو با گارانتی ۲ ساله',
    image: 'https://picsum.photos/seed/digital50/400/300',
    hasPhoto: true,
    date: '2024-05-01',
    views: 456,
    isActive: true,
  },

  // ===== خانه و آشپزخانه (50 آگهی) =====
  {
    id: 151,
    title: 'یخچال ساید بای ساید ال جی',
    price: 45000000,
    category: 'خانه و آشپزخانه',
    subCategory: 'لوازم خانگی برقی',
    city: 'تهران',
    district: 'جردن',
    description: 'یخچال با قابلیت آب یخ، یخ‌ساز، استیل ضد خش',
    image: 'https://picsum.photos/seed/home1/400/300',
    hasPhoto: true,
    date: '2024-06-19',
    views: 178,
    isActive: true,
  },
  {
    id: 152,
    title: 'مبل ۷ نفره استیل',
    price: 32000000,
    category: 'خانه و آشپزخانه',
    subCategory: 'مبلمان و صنایع چوب',
    city: 'کرج',
    district: 'گوهردشت',
    description: 'مبل با پارچه مخمل، پایه استیل، رنگ طوسی',
    image: 'https://picsum.photos/seed/home2/400/300',
    hasPhoto: false,
    date: '2024-06-17',
    views: 89,
    isActive: true,
  },
  {
    id: 153,
    title: 'ماشین لباسشویی سامسونگ ۱۲ کیلو',
    price: 28000000,
    category: 'خانه و آشپزخانه',
    subCategory: 'لوازم خانگی برقی',
    city: 'تهران',
    district: 'سعادت‌آباد',
    description: 'ماشین لباسشویی با موتور دیجیتال',
    image: 'https://picsum.photos/seed/home3/400/300',
    hasPhoto: true,
    date: '2024-06-16',
    views: 234,
    isActive: true,
  },
  {
    id: 154,
    title: 'سرویس خواب ۶ نفره مدرن',
    price: 15000000,
    category: 'خانه و آشپزخانه',
    subCategory: 'مبلمان و صنایع چوب',
    city: 'اصفهان',
    district: 'نقش جهان',
    description: 'سرویس خواب با طراحی مدرن و کیفیت بالا',
    image: 'https://picsum.photos/seed/home4/400/300',
    hasPhoto: true,
    date: '2024-06-15',
    views: 156,
    isActive: true,
  },
  {
    id: 155,
    title: 'فر برقی ال جی ۷۰ لیتری',
    price: 12000000,
    category: 'خانه و آشپزخانه',
    subCategory: 'لوازم خانگی برقی',
    city: 'تهران',
    district: 'پاسداران',
    description: 'فر برقی با ۱۰ برنامه پخت',
    image: 'https://picsum.photos/seed/home5/400/300',
    hasPhoto: true,
    date: '2024-06-14',
    views: 345,
    isActive: true,
  },
  {
    id: 156,
    title: 'کابینت آشپزخانه ممبران',
    price: 25000000,
    category: 'خانه و آشپزخانه',
    subCategory: 'مبلمان و صنایع چوب',
    city: 'تهران',
    district: 'شهرک غرب',
    description: 'کابینت با کیفیت بالا و گارانتی ۵ ساله',
    image: 'https://picsum.photos/seed/home6/400/300',
    hasPhoto: false,
    date: '2024-06-13',
    views: 189,
    isActive: true,
  },
  {
    id: 157,
    title: 'مایکروویو پاناسونیک ۳۲ لیتری',
    price: 8000000,
    category: 'خانه و آشپزخانه',
    subCategory: 'لوازم خانگی برقی',
    city: 'شیراز',
    district: 'معالی‌آباد',
    description: 'مایکروویو با قابلیت گریل',
    image: 'https://picsum.photos/seed/home7/400/300',
    hasPhoto: true,
    date: '2024-06-12',
    views: 234,
    isActive: true,
  },
  {
    id: 158,
    title: 'میز غذاخوری شیشه‌ای ۶ نفره',
    price: 9000000,
    category: 'خانه و آشپزخانه',
    subCategory: 'مبلمان و صنایع چوب',
    city: 'تهران',
    district: 'ونک',
    description: 'میز با پایه استیل و رویه شیشه‌ای',
    image: 'https://picsum.photos/seed/home8/400/300',
    hasPhoto: true,
    date: '2024-06-11',
    views: 156,
    isActive: true,
  },
  {
    id: 159,
    title: 'جاروبرقی رباتیک سامسونگ',
    price: 12000000,
    category: 'خانه و آشپزخانه',
    subCategory: 'لوازم خانگی برقی',
    city: 'تهران',
    district: 'جردن',
    description: 'جاروبرقی با نقشه‌برداری هوشمند',
    image: 'https://picsum.photos/seed/home9/400/300',
    hasPhoto: false,
    date: '2024-06-10',
    views: 345,
    isActive: true,
  },
  {
    id: 160,
    title: 'تخت چوبی ۲ نفره',
    price: 8000000,
    category: 'خانه و آشپزخانه',
    subCategory: 'مبلمان و صنایع چوب',
    city: 'اصفهان',
    district: 'چهارباغ',
    description: 'تخت با کیفیت بالا و طراحی کلاسیک',
    image: 'https://picsum.photos/seed/home10/400/300',
    hasPhoto: true,
    date: '2024-06-09',
    views: 234,
    isActive: true,
  },
  {
    id: 161,
    title: 'قهوه‌سازی نسپرسو',
    price: 6000000,
    category: 'خانه و آشپزخانه',
    subCategory: 'لوازم خانگی برقی',
    city: 'تهران',
    district: 'سعادت‌آباد',
    description: 'قهوه‌ساز با کپسول',
    image: 'https://picsum.photos/seed/home11/400/300',
    hasPhoto: true,
    date: '2024-06-08',
    views: 567,
    isActive: true,
  },
  {
    id: 162,
    title: 'کمد دیواری ۴ درب',
    price: 12000000,
    category: 'خانه و آشپزخانه',
    subCategory: 'مبلمان و صنایع چوب',
    city: 'تهران',
    district: 'پاسداران',
    description: 'کمد با طراحی مدرن',
    image: 'https://picsum.photos/seed/home12/400/300',
    hasPhoto: false,
    date: '2024-06-07',
    views: 189,
    isActive: true,
  },
  {
    id: 163,
    title: 'هود آشپزخانه ال جی',
    price: 7000000,
    category: 'خانه و آشپزخانه',
    subCategory: 'لوازم خانگی برقی',
    city: 'تهران',
    district: 'شهرک غرب',
    description: 'هود با قابلیت تنظیم ارتفاع',
    image: 'https://picsum.photos/seed/home13/400/300',
    hasPhoto: true,
    date: '2024-06-06',
    views: 234,
    isActive: true,
  },
  {
    id: 164,
    title: 'فرش ماشینی ۱۲ متری',
    price: 5000000,
    category: 'خانه و آشپزخانه',
    subCategory: 'مبلمان و صنایع چوب',
    city: 'شیراز',
    district: 'زند',
    description: 'فرش با طرح کلاسیک',
    image: 'https://picsum.photos/seed/home14/400/300',
    hasPhoto: true,
    date: '2024-06-05',
    views: 145,
    isActive: true,
  },
  {
    id: 165,
    title: 'چرخ خیاطی صنعتی',
    price: 15000000,
    category: 'خانه و آشپزخانه',
    subCategory: 'لوازم خانگی برقی',
    city: 'تهران',
    district: 'ونک',
    description: 'چرخ خیاطی با سرعت بالا',
    image: 'https://picsum.photos/seed/home15/400/300',
    hasPhoto: false,
    date: '2024-06-04',
    views: 89,
    isActive: true,
  },
  {
    id: 166,
    title: 'صندلی گیمینگ حرفه‌ای',
    price: 6000000,
    category: 'خانه و آشپزخانه',
    subCategory: 'مبلمان و صنایع چوب',
    city: 'کرج',
    district: 'گوهردشت',
    description: 'صندلی با قابلیت تنظیم ارتفاع',
    image: 'https://picsum.photos/seed/home16/400/300',
    hasPhoto: true,
    date: '2024-06-03',
    views: 234,
    isActive: true,
  },
  {
    id: 167,
    title: 'ماشین ظرفشویی بوش',
    price: 22000000,
    category: 'خانه و آشپزخانه',
    subCategory: 'لوازم خانگی برقی',
    city: 'تهران',
    district: 'جردن',
    description: 'ماشین ظرفشویی با تکنولوژی صرفه‌جویی',
    image: 'https://picsum.photos/seed/home17/400/300',
    hasPhoto: true,
    date: '2024-06-02',
    views: 456,
    isActive: true,
  },
  {
    id: 168,
    title: 'مبل راحتی ۳ نفره',
    price: 10000000,
    category: 'خانه و آشپزخانه',
    subCategory: 'مبلمان و صنایع چوب',
    city: 'اصفهان',
    district: 'خواجو',
    description: 'مبل با کیفیت بالا',
    image: 'https://picsum.photos/seed/home18/400/300',
    hasPhoto: true,
    date: '2024-06-01',
    views: 189,
    isActive: true,
  },
  {
    id: 169,
    title: 'آب‌سردکن پارس',
    price: 4000000,
    category: 'خانه و آشپزخانه',
    subCategory: 'لوازم خانگی برقی',
    city: 'تهران',
    district: 'سعادت‌آباد',
    description: 'آب‌سردکن با قابلیت گرم و سرد',
    image: 'https://picsum.photos/seed/home19/400/300',
    hasPhoto: false,
    date: '2024-05-30',
    views: 123,
    isActive: true,
  },
  {
    id: 170,
    title: 'قفسه کتاب ۵ طبقه',
    price: 3000000,
    category: 'خانه و آشپزخانه',
    subCategory: 'مبلمان و صنایع چوب',
    city: 'تهران',
    district: 'پاسداران',
    description: 'قفسه با طراحی مدرن',
    image: 'https://picsum.photos/seed/home20/400/300',
    hasPhoto: true,
    date: '2024-05-29',
    views: 234,
    isActive: true,
  },
  {
    id: 171,
    title: 'سشوار حرفه‌ای براون',
    price: 2000000,
    category: 'خانه و آشپزخانه',
    subCategory: 'لوازم خانگی برقی',
    city: 'تهران',
    district: 'شهرک غرب',
    description: 'سشوار با قابلیت تنظیم دما',
    image: 'https://picsum.photos/seed/home21/400/300',
    hasPhoto: true,
    date: '2024-05-28',
    views: 178,
    isActive: true,
  },
  {
    id: 172,
    title: 'میز آرایش با آینه',
    price: 5000000,
    category: 'خانه و آشپزخانه',
    subCategory: 'مبلمان و صنایع چوب',
    city: 'اصفهان',
    district: 'نقش جهان',
    description: 'میز آرایش با کشو و آینه',
    image: 'https://picsum.photos/seed/home22/400/300',
    hasPhoto: false,
    date: '2024-05-27',
    views: 145,
    isActive: true,
  },
  {
    id: 173,
    title: 'اتو بخار فیلیپس',
    price: 3000000,
    category: 'خانه و آشپزخانه',
    subCategory: 'لوازم خانگی برقی',
    city: 'تهران',
    district: 'ونک',
    description: 'اتو با قابلیت بخار عمودی',
    image: 'https://picsum.photos/seed/home23/400/300',
    hasPhoto: true,
    date: '2024-05-26',
    views: 234,
    isActive: true,
  },
  {
    id: 174,
    title: 'شومیزه برقی دیواری',
    price: 8000000,
    category: 'خانه و آشپزخانه',
    subCategory: 'لوازم خانگی برقی',
    city: 'تهران',
    district: 'جردن',
    description: 'شومیزه با شعله مصنوعی',
    image: 'https://picsum.photos/seed/home24/400/300',
    hasPhoto: true,
    date: '2024-05-25',
    views: 345,
    isActive: true,
  },
]